apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  project: default
  destination:
    name: "in-cluster"
    namespace: monitoring
  sources:
    - repoURL: https://github.com/tomoconnor/home-assistant-helm-chart.git
      targetRevision: v0.1
      path: charts/home-assistant
      # chart: home-assistant
      helm:
        valueFiles:
          - $values/homeassistant.values.yaml
    - repoURL: "https://github.com/tomoconnor/argocd-helm-values.git"
      targetRevision: HEAD
      ref: values
    