apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apcupsd-exporter
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  project: default
  destination:
    name: "in-cluster"
    namespace: monitoring
  sources:
    - repoURL: https://github.com/tomoconnor/homelab-helm-charts.git
      targetRevision: HEAD
      path: genericapp
      helm:
        valueFiles:
          - $values/apcupsd_exporter.values.yaml
    - repoURL: "https://github.com/tomoconnor/argocd-helm-values.git"
      targetRevision: HEAD
      ref: values
    