apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smokeping
  namespace: argocd
spec:
  project: default
  destination:
    server: "in-cluster"
    namespace: monitoring
  sources:
    - repoURL: https://djjudas21.github.io/charts/
      targetRevision: 0.1.3
      chart: smokeping
      helm:
        valueFiles:
          - $values/smokeping.values.yaml
    - repoURL: "https://github.com/tomoconnor/argocd-helm-values.git"
      targetRevision: HEAD
      ref: values
    